CI: rename linux job and add run job for zephyr
Signed-off-by: SorinO <sorin.olari2@gmail.com>

diff --git a/.github/workflows/zephyr.yml b/.github/workflows/zephyr.yml
--- a/.github/workflows/zephyr.yml
+++ b/.github/workflows/zephyr.yml
@@ -89,3 +89,41 @@ jobs:
             echo "[ERROR] Expected log not found: $EXPECTED_LOG"
             exit 1
           fi
+
+  run-zephyr:
+    name: Zephyr Run
+    needs: build-zephyr
+    runs-on: ["self-hosted", "build-server"]
+    container:
+      image: ghcr.io/${{ github.repository }}/devcontainer-zephyr:${{ inputs.devcontainer-tag }}
+      options: --user 1000:1000
+    strategy:
+      matrix:
+        board:
+          - native_sim/native/64
+        app:
+          - mini
+
+    steps:
+      - name: Set sane board name
+        run: |
+          BOARD=${{ matrix.board }}
+          echo "BOARD_NAME=$(printf "%s\n" "$BOARD" | tr / _)" >> $GITHUB_ENV
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: ocre-zephyr-${{ env.BOARD_NAME }}-${{ matrix.app }}
+
+      - name: Run ${{ matrix.board }} ${{ matrix.app }}
+        run: |
+          EXPECTED_LOG="powered by Ocre"
+          echo "Running application..."
+          stdbuf -oL -eL timeout 20s ./build/zephyr/zephyr.exe | tee zephyr_run.log
+          echo "===== Checking for expected log ====="
+          if grep -q "$EXPECTED_LOG" zephyr_run.log; then
+            echo "[OK] Found expected log: $EXPECTED_LOG"
+          else
+            echo "[ERROR] Expected log not found: $EXPECTED_LOG"
+            exit 1
+          fi
